application: js-interop-issue
version: 1
runtime: go
api_version: go1

inbound_services:
- channel_presence

handlers:
# Handler for js scripts
# These are needed when running 'pub build' output
- url: /.*packages/(.*\.js|.*\.svg)
  static_files: web/build/web/packages/\1
  upload: web/build/web/packages/(.*\.js|.*\.svg)

- url: /.*/(.*\.js)
  static_files: web/build/web/\1
  upload: web/build/web/(.*\.js)

- url: /(.*\.js)
  static_files: web/build/web/\1
  upload: web/build/web/(.*\.js)

# All other requests are handled by the Go code
- url: /.*
  script: _go_app
  secure: always
